name: Production

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm test
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: ${{ secrets.HOST }}
        # FTP user
        user: ${{ secrets.USER }}
        # FTP password
        password: ${{ secrets.PASSWORD }}
        # Local directory
        localDir: ./build
        # Remote directory
        remoteDir: ./www/interquiz.ru/mementor
